# Generated by Django 3.0.7 on 2020-06-14 20:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Query',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hash', models.CharField(blank=True, max_length=64, null=True)),
                ('query', models.CharField(max_length=128)),
                ('sources', models.CharField(blank=True, max_length=128, null=True)),
                ('domains', models.CharField(blank=True, max_length=128, null=True)),
                ('from_date', models.DateField(blank=True, null=True)),
                ('to_date', models.DateField(blank=True, null=True)),
                ('language', models.CharField(blank=True, max_length=32, null=True)),
                ('sorting', models.CharField(blank=True, max_length=32, null=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True, null=True)),
                ('total_pages', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'verbose_name_plural': 'Queries',
            },
        ),
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('page', models.IntegerField(blank=True, null=True)),
                ('source', models.CharField(blank=True, max_length=256, null=True)),
                ('author', models.CharField(blank=True, max_length=256, null=True)),
                ('title', models.CharField(blank=True, max_length=1024, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('url', models.URLField(blank=True, null=True)),
                ('published_at', models.DateField(blank=True, null=True)),
                ('content', models.TextField(blank=True, null=True)),
                ('query', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='main.Query')),
            ],
        ),
    ]
